name: Devops Lab

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      # creates login using github secretes
      - name: Log into docker hub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      # build the docker image. Using '.' because working from root dir
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/devops-lab .

      # pushes to docker hub to build image
      - name: Publish docker image to docker hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/devops-lab:latest